title: "Samuel Holmes"
description: "Computer Simulations to Accelerate the Design of Polymeric Materials"
theme: jekyll-theme-minimal
tags: [md-simulation, cellulose, force-field, thermoplastic, AMBER, GLYCAM, glycomaterials]
